# Generated by Django 4.2.5 on 2023-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productordercount',
            name='count',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
