# Generated by Django 4.2.5 on 2023-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_remove_order_user_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.SmallIntegerField(),
        ),
    ]
