# Generated by Django 4.2.5 on 2023-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='products.product', verbose_name='Товар'),
        ),
    ]
