# Generated by Django 4.2.5 on 2023-09-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_review_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.product'),
        ),
    ]
