# Generated by Django 4.2.5 on 2023-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_images_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(related_name='tag', to='products.product'),
        ),
    ]
