# Generated by Django 4.2.5 on 2023-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_tag_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(related_name='tags', to='products.product'),
        ),
    ]
