# Generated by Django 4.2.5 on 2023-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_specifications_product_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='products.tag'),
        ),
    ]
