# Generated by Django 4.2.5 on 2023-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_tag_product_tagg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tagg',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='products.tag'),
        ),
    ]
