# Generated by Django 4.2.5 on 2023-09-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='scr',
            new_name='src',
        ),
    ]
