# Generated by Django 4.2.5 on 2023-10-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_image_profileavatar_src_profileavatar_alt'),
        ('products', '0022_rename_scr_productimage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profiles'),
        ),
    ]
