# Generated by Django 4.2.5 on 2023-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(),
        ),
    ]
