# Generated by Django 4.2.5 on 2023-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_sale_datefrom_alter_sale_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(blank=True),
        ),
    ]
