# Generated by Django 4.2.5 on 2023-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_categories_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='categories',
            name='subcategories',
            field=models.ManyToManyField(null=True, related_name='categories', to='catalog.categories'),
        ),
    ]
