# Generated by Django 4.2.5 on 2023-09-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_categories_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='categories',
            name='subcategories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categories'),
        ),
    ]
