# Generated by Django 4.2.5 on 2023-09-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_categories_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.categories'),
        ),
    ]
