# Generated by Django 4.2.5 on 2023-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_categories_subcategories_categories_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPage', models.CharField(max_length=4)),
                ('lastPage', models.CharField(max_length=4)),
            ],
        ),
    ]
