# Generated by Django 4.2.5 on 2023-10-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_scr_productimage_src'),
        ('catalog', '0006_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product'),
            preserve_default=False,
        ),
    ]
