# Generated by Django 4.2.5 on 2023-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_catalog_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
