# Generated by Django 4.2.5 on 2023-11-22 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to=profiles.models.profile_avatar_path, verbose_name='Путь')),
                ('alt', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Изображение профиля',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profileavatar', verbose_name='Изображение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='profileavatar',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='profiles.profiles', verbose_name='Профиль'),
        ),
    ]
