# Generated by Django 4.2.5 on 2023-10-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileavatar',
            old_name='image',
            new_name='src',
        ),
        migrations.AddField(
            model_name='profileavatar',
            name='alt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
